/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3D/shirt.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/shirt.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_6.geometry} material={materials.Body_FRONT_2664} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.Body_FRONT_2664} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.Body_FRONT_2664} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.Body_FRONT_2664} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.Body_FRONT_2664} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.Body_FRONT_2664} />
      <mesh geometry={nodes.Object_15.geometry} material={materials.Body_FRONT_2664} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.Body_FRONT_2664} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.Sleeves_FRONT_2669} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.Sleeves_FRONT_2669} />
    </group>
  )
}

useGLTF.preload('/shirt.glb')
